BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_miles


        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'up'
            Button:
                text:'down'

    Button:
        text: 'Convert miles to km'

    Label:
        id: output_label
        color: (1, 1, 0, 1)



